jobs:
  build:
    runs-on: "ubuntu-24.04"
    steps:
    - uses: "actions/checkout@v6"
    - uses: "actions/setup-dotnet@v5"
      with:
        global-json-file: "global.json"
    - uses: "actions/setup-node@v6"
      with:
        node-version: "24"
    - run: "dotnet restore"
    - run: "dotnet build"
    - run: "dotnet test"
    - run: "dotnet publish"
name: "main"
on:
  pull_request:
    branches: [ "main", "release" ]
  push:
    branches: [ "main", "release" ]
